### ISSUE TITLE
Difference between code and paper 

### ISSUE THREAD

**Issue by ldz666666** [theEricMa/OTAvatar#12]
Hi, thanks for your great work !
In [line 730 of decouple_by_invert.py](https://github.com/theEricMa/OTAvatar/blob/548ba7ebfcbbec78e6503f0ef3b2d0e63d83da36/trainers/decouple_by_invert.py#L730), the parameter of the motion controller is updated together with the eg3d generator.
However, in the algorithm of the appendix, the parameters of the motion controller is not updated while finetuning theta_eg
<img width="336" alt="截屏2023-05-15 16 50 00" src="https://github.com/theEricMa/OTAvatar/assets/41360226/5e686c50-8924-4616-98e4-56dfad348fcb">
By the way, in the 16th line of the algorithm, `Lt` is not mentioned in the original paper, is there a mistake?

**Comment by theEricMa** [comment]
Thanks for reminding us the typo! We did update `\theta_c$` while finetuning `$theta_eg$`, and the `Lt` should be `Ld`. Please be subject to the code, it shows what we want to express in the paper.
