### ISSUE TITLE
cann

### ISSUE THREAD

**Issue by yuzhou164** [theEricMa/OTAvatar#2]
Nice Work!
When runing the inference_refine_1D_cam.py file, the error is unknown location of config file. 
Indeed, the config file cannot be found under the file Config.
![image](https://user-images.githubusercontent.com/2318194/230373891-9c200a4a-bcbd-4ce8-bbec-a75701e086b8.png)

**Comment by yuzhou164** [comment]
Nice Work!
When runing the inference_refine_1D_cam.py file, the error is unknown location of config file .

**Comment by theEricMa** [comment]
Hi, I uploaded the missing file together with the dataset. Please see the updated Readme for detail. For any other questions, please feel free to update your question here.

**Comment by liangshuang1993** [comment]
@theEricMa still missing **hdtf_cross_id.py**

**Comment by sunshineatnoon** [comment]
By the way, it seems the [Google drive link](https://drive.google.com/drive/folders/1ce9o_iB5v9oqmxop3Qn-pCXP60YdxURq?usp=share_link) for processed data is not accessible.

**Comment by 87003697** [comment]
@baihei-1122 If you really want to extract the image data from the .mdb file, my advice is to traverse the .mdb file by modifiying the dataset object https://github.com/theEricMa/OTAvatar/blob/6e468be835b4123b08dfdbd12e378ef3abc7aeb4/data/dataset.py#L24 and save every image using cv2 or PIL.Image,

**Comment by baihei-1122** [comment]
@theEricMa much thanks!

**Comment by theEricMa** [comment]
@baihei-1122 please check my updated readme on how to abtain the .pth file

**Comment by baihei-1122** [comment]
@theEricMa , thanks, I have found this script and convert to `.pth` file and I adjust the `G_new.neural_rendering_resolution =64`, through the output video it seems success. But I meet the new problem with miss this file `pretrained/ws_std.npy` which in  `trainers/decouple_by_invert.py`

**Comment by 87003697** [comment]
@baihei-1122 I uploaded it, you can pull the latest repo

**Comment by sunshineatnoon** [comment]
@theEricMa Hi, thanks for the update. Could you please share the pre-processed data through google drive or zip them in the Baidu Netdisk? It is hard to download a raw folder from Baidu Netdisk. Thanks!

**Comment by baihei-1122** [comment]
@theEricMa thanks bro!

**Comment by amerssun** [comment]
> @theEricMa thanks bro! But I meet the new error, it seems like miss the checkpoint.
> 
> ```
> We train Generator
> No checkpoint found at iteration 2000.
> ```
> 
> through the message I found it located at `inference_refine_1D_cam.py - trainer.load_checkpoint`

hi, Have you trained this model？ I'm curious about how well this model works

**Comment by theEricMa** [comment]
> @theEricMa Hi, thanks for the update. Could you please share the pre-processed data through google drive or zip them in the Baidu Netdisk? It is hard to download a raw folder from Baidu Netdisk. Thanks!

We have uploaded the zipped file in Google Drive, thanks for your advice!

**Comment by theEricMa** [comment]
> > @theEricMa thanks bro! But I meet the new error, it seems like miss the checkpoint.
> > ```
> > We train Generator
> > No checkpoint found at iteration 2000.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > through the message I found it located at `inference_refine_1D_cam.py - trainer.load_checkpoint`
> 
> hi, Have you trained this model？ I'm curious about how well this model works

The model is uploaded now. Please check the Readme, thanks!
