### ISSUE TITLE
Makes face animation with specified image

### ISSUE THREAD

**Issue by 904763189cy** [theEricMa/OTAvatar#25]
Hi!
Since the project(OTAvatar_processing) only handles video types. I converted an the specified image into a video with 120 frames(duplicate). Then I obtained data(target video and source video(specified image)) in mdb format through Project OTAvatar_processing.  

After running project OTAvatar, the obtained results are as follows：

Uploading video_target_to_video_source.mp4…
https://github.com/theEricMa/OTAvatar/assets/117260350/48f089c3-6b13-4712-85e7-4ad71a747325

The results are not very satisfactory.  I don’t know if I made mistakes in processing the images.
Thanks!

**Comment by 904763189cy** [comment]
https://github.com/theEricMa/OTAvatar/assets/117260350/33e009bd-2518-426a-89e1-76ed5a7eda00

**Comment by 904763189cy** [comment]
https://github.com/theEricMa/OTAvatar/assets/117260350/43627c6a-69bd-445a-bcec-243073126548

**Comment by 904763189cy** [comment]
Sorry, the uploaded video cannot be played.
I think the lack of good results is due to my incorrect handling of specific images. 
How should I handle specific images?

**Comment by 904763189cy** [comment]
Solved

**Comment by alakhsharmaa** [comment]
@904763189cy How is OTAvatar_processing used?
