### ISSUE TITLE
Pretrained model batchsize and gpus

### ISSUE THREAD

**Issue by szh-bash** [theEricMa/OTAvatar#29]
Hi, may I know how much GPU is used for the training? Mine is 4 A100s (80GB mem), so the batchsize is 8(per GPU) * 4 (GPU num) = 32, therefore the 2000 iters will spend more than 1 epoch. If you cannot support batchsize=8 per GPU, please try more GPUs. Larger batchsize leads to more stable training.  

_Originally posted by @theEricMa in https://github.com/theEricMa/OTAvatar/issues/10#issuecomment-1537972669_

I trained with 4(per GPU) * 6(GPU num), 1500 iters spent exactlly 1 epoch.
![image](https://github.com/theEricMa/OTAvatar/assets/27895812/33a254b7-c062-44ba-b568-e90349a897cd)
The [pretrained model](https://drive.google.com/file/d/1JW1ieAgeu5qugC41O7zjn7IA49Jfnytt/view?usp=share_link) named epoch_00005_iteration_000002000, maybe you trained this model with more than 8(per GPU) * 8(GPU num)?

**Comment by theEricMa** [comment]
Hello, thanks for the feedback. The training configuration has been optimized for typical GPUs with 24-32GB memory. However, we used 80GB A100 GPUs which allowed much larger batch sizes. Feel free to modify the configs as needed to fit your hardware.
