### ISSUE TITLE
can you share your pretrained model?

### ISSUE THREAD

**Issue by amerssun** [theEricMa/OTAvatar#5]
can you share your pretrained model?

And when doing inference,i met this error  :
python: /opt/conda/conda-bld/magma-cuda113_1619629459349/work/interface_cuda/interface.cpp:899: void magma_queue_create_from_cuda_internal(magma_device_t, cudaStream_t, cublasHandle_t, cusparseHandle_t, magma_queue**, const char*, const char*, int): Assertion `queue->dBarray__ != __null' failed.

![image](https://user-images.githubusercontent.com/14248498/232506356-4ac229a0-d573-4bf9-9677-6c3219aaed57.png)

**Comment by theEricMa** [comment]
Hi, the model weight is now uploaded. As for the error, I haven't seen this one before. Our code is based on [PIRender](https://github.com/RenYurui/PIRender) and [EG3D](https://github.com/NVlabs/eg3d), you can check if the same question exists in their repositories.
