### ISSUE TITLE
ModuleNotFoundError: No module named 'third_part'

### ISSUE THREAD

**Issue by szh-bash** [theEricMa/OTAvatar#9]
Both train/inference stuck here, I dont know how many missing files left, maybe you could check them in another clean machine?

```
  File "/home/x/OTAvatar/util/lpips.py", line 8, in <module>
    from third_part.PerceptualSimilarity.models import dist_model as dm
ModuleNotFoundError: No module named 'third_part'
```

BTW, there're some missing python packages in enviroment.yaml: opencv-python  traitlets PyYAML  lmdb

**Comment by jaslee20** [comment]
You can get all the files from pirenderer 
https://github.com/RenYurui/PIRender

**Comment by szh-bash** [comment]
> You can get all the files from pirenderer https://github.com/RenYurui/PIRender

Thanks bro! Everything works now!

**Comment by theEricMa** [comment]
The module is uploaded, thanks everyone!
